export const CONTACT_MAIL_SEND_SUCCESS = 'CONTACT_MAIL_SEND_SUCCESS';
export const CONTACT_MAIL_SEND_FAIL = 'CONTACT_MAIL_SEND_FAIL';
export const CONTACT_MAIL_SEND_REQUEST = 'CONTACT_MAIL_SEND_REQUEST';

export const CLEAR_ERRORS = "CLEAR_ERRORS"